# Generated by Django 4.1 on 2023-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_service_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="service_request",
            name="field",
            field=models.CharField(
                choices=[
                    ("Air Conditioner", "Air Conditioner"),
                    ("All in One", "All in One"),
                    ("Carpentry", "Carpentry"),
                    ("Electricity", "Electricity"),
                    ("Gardening", "Gardening"),
                    ("Home Machines", "Home Machines"),
                    ("House Keeping", "House Keeping"),
                    ("Interior Design", "Interior Design"),
                    ("Locks", "Locks"),
                    ("Painting", "Painting"),
                    ("Plumbing", "Plumbing"),
                    ("Water Heaters", "Water Heaters"),
                ],
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
